version: "3"
services:
  app:
    build: .
    env_file: .env
    depends_on:
      - postgres
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/home/app/uploads
    environment:
      NODE_ENV: production

  postgres:
    container_name: barbers-pg
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: barbers
      POSTGRES_PASSWORD: barbers
    ports:
      - "5425:5432"
